config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :comments, only: %i[show create new edit update destroy]
  resources :answers

  get '/user', to: "designs#index", as: :user_root
  resources :designs
  get '/all_designs', to: 'designs#all_designs', as: :all_designs
  resources :requests, only: %i[new show edit update create destroy]
  get '/requests', to: 'requests#all_requests', as: :all_requests
  get '/new_project', to: 'requests#new_project', as: :new_project

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/design.rb
class Design < ApplicationRecord
  belongs_to :user
  has_one_attached :document
  has_many :request
  has_many :comment, dependent: :destroy
  validates :project_number, uniqueness: { message: 'Numero de proyecto ya registrado'}
  include PgSearch::Model
  pg_search_scope :global_search,
    against: %i[project_number project_name responsible],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show,:edit,:update,:destroy]
  def index
    @user = current_user
    case @user.role
    when 'employee'
      @designs = policy_scope(search_bar_employee)
    when 'production_manager', 'engineering_manager'
      @designs = policy_scope(search_bar_production)
    when 'engineer'
      @designs = policy_scope(search_bar_engineer)
    end
  end

  def search_bar_employee
    params[:query].present? ? (@designs = Design.where("project_number LIKE '%#{params[:query]}%' OR project_name LIKE '%#{params[:query].upcase}%'")) : (@designs = Design.where(status: 'activo'))
  end

  def search_bar_production
    params[:query].present? ? (@designs = Design.where("project_number LIKE '%#{params[:query]}%' OR project_name LIKE '%#{params[:query].upcase}%'")) : (@designs = Design)
  end

  def search_bar_engineer
    @user = current_user
    params[:query].present? ? (@designs = Design.where("project_number LIKE '%#{params[:query]}%' OR project_name LIKE '%#{params[:query].upcase}%'")) : (Design.where(status: 'activo', responsible: @user.responsible))
  end

  def all_designs
    @user = current_user
    case @user.role
    when 'production_manager', 'engineering_manager'
      @designs = Design.all
    when 'engineer'
      @designs = Design.where(responsible: @user.responsible).order("updated_at DESC")
    end
    authorize @designs
  end

  def new
    @design = Design.new
    @user = current_user
    @users = User.where(role: 'engineer')
    authorize @design
  end

  def create
    @design = Design.new(design_params)
    @user = current_user
    @users = User.where(role: 'engineer')
    authorize @design
    if @design.save
      redirect_to @design
    else
      render "new"
    end
  end

  def edit
    @user = current_user
    @users = User.where(role: 'engineer')
    @responsible = @design.responsible
  end

  def show
    @user = current_user
    @comment = Comment.new
    @comments = Comment.where(design_id: params[:id]).order(id: :desc)
    @hcc = Comment.where(design_id: params[:id]).where(hcc: "activo")
    @hccs = Comment.where(design_id: params[:id]).where(hcc: "activo").count
    @comments_count = Comment.where(design_id: params[:id]).count
    @count_photo = 0
    @comments.each do |photos_count|
      photos_count.annex.present? ? @count_photo += 1 : next
    end
    @allphotos = []
    @comments.each do |all|
      all.annex.present? ? @allphotos.push(all.annex) : next
    end
    @lastphotos = []
    @allphotos.each_with_index do |last, index|
      if index <= 3
        last.present? ? @lastphotos.push(last) : next
      end
    end
    @answer = Answer.new
    @answers = Answer.all.order(id: :desc)
  end

  def update
    @design.update(design_params)
    @user = current_user
    case @user.role
    when 'production_manager', 'engineering_manager'
      redirect_to all_designs_path
    when 'engineer'
      redirect_to @design
    end
  end

  def destroy
    @design.destroy
    redirect_to designs_path
  end

  private

  def set_design
    @design = Design.find(params[:id])
    authorize @design
  end

  def design_params
    params.require(:design).permit(
      :project_number, :client,
      :project_name, :responsible,
      :revision, :line,
      :status, :autodesk_link,
      :server_path, :user_id,
      :document
    )
  end
end

app/views/designs/_designs_form.html.erb
<%= simple_form_for(design) do |f| %>
<% case @user.role %>
    <% when "production_manager"  %>
    <%# Production manager case starts %>
    <div class="container register" id="test-div-form">
        <div class="row">
            <div class="col-md-3 register-left">
                <%= image_tag "favicon.ico" %>
                <h3>Hola, <%= @user.responsible %></h3>
                <p class="text-light">Ingresa los datos de tu diseño.</p>
                <div class="d-flex justify-content-between">
                  <%= f.submit "Guardar" %>
                  <%= link_to "Cancelar", designs_path, class: "btn btn-outline-light rounded-pill" %>
                </div>
            </div>

            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Crear o editar un diseño</h3>
                        <div class="row register-form">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <%= f.input :project_number, input_html: {value: design.project_number, readonly: "readonly" }, placeholder: "Número de proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                    <%= f.input :client, input_html: {value: design.client, readonly: "readonly" }, placeholder: "Cliente", label: false %>
                                </div>

                                <div class="form-group">
                                    <%= f.input :line, placeholder: "Linea de producción", label: false %>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <%= f.input :project_name, input_html: {value: design.project_name, readonly: "readonly" }, placeholder: "Nombre del proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                    <%= f.input :revision, input_html: {value: design.revision, readonly: "readonly" }, placeholder: "Número de revisión del plano", label: false %>
                                </div>
                                <div class="form-group">
                                     <% if design.status == 'activo' %>
                                        <div class="form-check form-switch">
                                        <%= f.input :status, class: "form-check-input", label: "Activo",
                                                    as: :boolean,
                                                    checked_value: "activo",
                                                    unchecked_value: "inactivo",
                                                    input_html: {
                                                      checked: design.status == "activo" ? "checked" : "" #this line changes the status of the checkbox
                                                    } %>
                                          </div>
                                      <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <%# Production manager case ends %>

        <%# Engineer case starts %>
      <% when "engineer" %>
      <div class="container register" id="test-div-form">
        <div class="row">
            <div class="col-md-3 register-left">
                <%= image_tag "favicon.ico" %>
                <h3>Hola, <%= @user.responsible %></h3>
                <p class="text-light">Ingresa los datos de tu diseño.</p>
                <div class="d-flex justify-content-between">
                  <%= f.submit "Guardar" %>
                  <%= link_to "Cancelar", designs_path, class: "btn btn-outline-light rounded-pill" %>
                </div>
            </div>

            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Crear o editar un diseño</h3>
                        <div class="row register-form">
                            <div class="col-md-6">
                                <div class="form-group">
                                  <%= f.input :project_number, placeholder: "Número de proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :client, placeholder: "Cliente", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :project_name, placeholder: "Nombre del proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :revision, placeholder: "Número de revisión del plano", label: false %>
                                </div>
                                <div class="form-group">
                                    <%= f.input :server_path, placeholder: "Ruta del servidor", label: false %>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                  <%= f.input :responsible, input_html: {value: @user.responsible, readonly: "readonly" }, placeholder: "Ingeniero a cargo: ", label: false  %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :autodesk_link, placeholder: "Link del visor 3D", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= link_to "Cargar modelo 3D", "https://viewer.autodesk.com/", target: "_blank", class: "btn btn-outline-dark rounded-pill"  %>
                                </div>
                                <br>
                                <div class="form-group">
                                  <%= f.file_field :document, class: "form-control" %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <%# Engineer case ends %>

        <%# Engineer manager case starts %>
      <% when "engineering_manager" %>
      <div class="container register" id="test-div-form">
        <div class="row">
            <div class="col-md-3 register-left">
                <%= image_tag "favicon.ico" %>
                <h3>Hola, <%= @user.responsible %></h3>
                <p class="text-light">Ingresa los datos de tu diseño.</p>
                <div class="d-flex justify-content-between">
                  <%= f.submit "Guardar" %>
                  <%= link_to "Cancelar", :back, class: "btn btn-outline-light rounded-pill" %>
                </div>
            </div>

            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Crear o editar un diseño</h3>
                        <div class="row register-form">
                            <div class="col-md-6">
                                <div class="form-group">
                                  <%= f.input :project_number, placeholder: "Número de proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :client, placeholder: "Cliente", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :project_name, placeholder: "Nombre del proyecto", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :revision, placeholder: "Número de revisión del plano", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :line, placeholder: "Linea de producción", label: false %>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                  <%= f.select :responsible, options_for_select(@users.collect{ |u| [u.responsible, u.responsible] }, @responsible),{}, {class: "form-select mb-3"} %>
                                </div>
                                <div class="form-group">
                                  <%= f.input :autodesk_link, placeholder: "Link del visor 3D", label: false %>
                                </div>
                                <div class="form-group">
                                  <%= link_to "Cargar modelo 3D", "https://viewer.autodesk.com/", target: "_blank", class: "btn btn-outline-dark rounded-pill"  %>
                                </div>
                                <br>
                                <div class="form-group">
                                  <%= f.file_field :document, class: "form-control", accept: 'application/pdf,' %>
                                </div>
                                <br>
                                <div class="form-group">
                                  <div class="form-check form-switch">
                                  <%= f.input :status, class: "form-check-input", label: "Activo",
                                              as: :boolean,
                                              checked_value: "activo",
                                              unchecked_value: "inactivo",
                                              input_html: {
                                                checked: design.status == "activo" ? "checked" : "" #this line changes the status of the checkbox
                                              } %>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
        <%# Engineer manager case end %>
  <% end %>
  <%= f.input :user_id, label: false, input_html: {value: @user.id, readonly: "readonly", class: 'visually-hidden' }  %>
<% end %>

app/views/designs/all_designs.html.erb
<div class="header">

  <!--Content before waves-->
  <div class="inner-header flex">
    <h1>Todos los diseños</h1>
  </div>

  <!--Waves Container-->
  <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7)" />
    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
    <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
    </svg>
  </div>
  <!--Waves end-->

</div>
<!--Header ends-->

<div class="d-flex flex-column" id="home-icon">
  <%= link_to image_tag("home"), designs_path%>
  <p>Regresar al inicio</p>
</div>




<div class="container shadow-lg p-3 mb-5 bg-body rounded" >
  <table class="table table-bordered table-striped table-hover" id="example">
    <thead class= "">
      <tr>
        <th scope="col">No. Proyecto</th>
        <th scope="col">Cliente</th>
        <th scope="col">Nombre del proyecto</th>
        <th scope="col">Revisión</th>
        <th scope="col">Última modificación</th>
        <th scope="col">Estatus</th>
        <th scope="col">Plano</th>
        <th scope="col">3D</th>
        <th scope="col">  </th>
      </tr>
    </thead>
    <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td> <%= link_to design.project_number, design_path(design), class: "btn btn-outline-dark" %> </td>
        <td> <%= design.client %> </td>
        <td> <%= design.project_name %> </td>
        <td> <%= design.revision %> </td>
        <td> <%= design.updated_at.localtime.to_formatted_s(:db) %> </td>
        <td> <%= design.status %> </td>
        <% if design.document.present? %>
          <td> <%= link_to "SI", design.document, target: :_blank %> </td>
        <% else %>
          <td> NO </td>
        <% end %>
        <% if design.autodesk_link.present? %>
          <td> <%= link_to "SI", design.autodesk_link, target: :_blank%> </td>
        <% else %>
          <td> NO </td>
        <% end %>
        <td class="align-middle"> <%= link_to "", edit_design_path(design), class: "bi bi-pencil-square", style: "z-index: 1;" %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/designs/edit.html.erb
<%= render "designs_form", design: @design %>

app/views/designs/index.html.erb
<%= render 'shared/sidebar' %>

<!--Hey! This is the original version
of Simple CSS Waves-->

<div class="header">

  <!--Content before waves-->
  <div class="inner-header flex">
    <h1>Diseños Activos</h1>
  </div>

  <!--Waves Container-->
  <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7)" />
    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
    <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
    </svg>
  </div>
  <!--Waves end-->

</div>
<!--Header ends-->



<div class="row d-flex justify-content-end m-3" id="">

  <% if @user.role = 'employee'%>
  <div class="col-lg-6 col-md-12">
    <p class="text-end fs-2 mx-5 ">Bienvenido, <%= @user.responsible %></p>
  </div>
  <% end %>

  <% if policy(Design).create? && @user.role != 'employee' && @user.role != 'production_manager'  %>
    <%= link_to (image_tag "new-design", class: "button-images") + "  Nuevo diseño", new_design_path, class: 'align-self-center rounded-pill m-5 main-btn-designs' %> <br>
  <% end %>
  <div class="col-lg-4 col-md-12 m-2">
  <%= form_tag designs_path, id: "content", method: :get, class: "d-flex justify-content-between" do %>
  <%= text_field_tag :query, params[:query], class: "form-control", id: "floatingInput", placeholder: "Buscar un diseño" %>
  <button type="search" class="btn btn-outline-primary" id="search-btn">Buscar</button>
  <%= link_to "Reestablecer", designs_path, class: "btn btn-outline-secondary" %>
  </div>
  <% end %>

</div>

<div class="d-flex">
  <div class="container vertical-scrollable" id="designs-cards">
    <div class="row">
      <%  @designs.each do |design|%>
        <div class="card-product">
          <% if design.document.present? %>
            <%= link_to (image_tag design.document.preview(resize_to_limit: [200, 200])), design.document, target: :_blank, class: "none" %>
          <% else %>
            <%= image_tag 'BIOIN-screen.png', class: "none" %>
          <% end %>
          <div class="card-product-infos">
            <h2><%= design.project_number %></h2>
            <p><%= design.project_name %><strong> | Revisión: <%= design.revision %></strong></p>
          </div>
          <div class="card-buttons">
            <% if @user.role == 'engineer' || @user.role == 'production_manager' %>
              <h6> <%= link_to "Editar ✏️", edit_design_path(design), class: "btn btn-outline-dark rounded-pill" %> </h6>
            <% end %>
            <h6> <%= link_to "Ver 🔎", design_path(design), class: "btn btn-outline-dark rounded-pill" %> </h6>
            <% if design.autodesk_link.present? %>
              <h6> <%= link_to "3D 🧊", design.autodesk_link, target: :_blank, class: "btn btn-outline-dark rounded-pill" %> </h6>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/designs/new.html.erb
<%= render "designs_form", design: @design %>

app/views/designs/show.html.erb
<%# profile starts %>
<section class="h-100 gradient-custom-2">
  <div class="py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="container px-5">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #414142;">
            <div class="ms-4 mb-3 mt-5 d-flex flex-column col-md-3 align-self-center" style="width: 150px;">
              <%= link_to "← Regresar", designs_path, class: "btn btn-outline-light mt-2" %>
              <% if policy(@design).edit? && @user.role == "engineer" && @user.responsible == @design.responsible || @user.role == "engineering_manager"%>
                <%= link_to "Editar", edit_design_path(@design), class: "btn btn-outline-light mt-2", style: "z-index: 1;" %>
              <% end %>
              <% if @user.role == "engineering_manager" && policy(@design).destroy? %>
                <%= link_to "Eliminar", design_path(@design), method: "delete", class: "btn btn-outline-light mt-2", style: "z-index: 1;" %>
              <% end %>
            </div>
            <div class="ms-4 mb-3 mt-5 d-flex flex-column col-md-4 align-self-center ">
              <div>
                <h2 class="text-center"><%=  @design.project_number  %></h2>
                <h5 class="text-center"><%=  @design.project_name  %></h5>
                <p class="text-light text-center"><%=  @design.client  %></p>
                <div class="d-grid gap-2 mx-auto">
                <%= link_to "3D 🧊", @design.autodesk_link, target: :_blank, class: "btn btn-outline-light rounded-pill mx-auto" %>
                </div>
              </div>
            </div>
            <div class="ms-5 col-md-6 d-flex align-items-center">
            <% if @design.document.present? %>
                <%= link_to (image_tag @design.document.preview(resize_to_limit: [500, 500]), class: "img-fluid img-thumbnail mt-4 mb-3 mx-auto none"), @design.document, target: :_blank %>
              <% else %>
                <%= image_tag "BIOIN-screen.png", style: "width: 250px; height: auto; z-index: 1", class: "img-fluid img-thumbnail mt-4 mb-3 none" %>
              <% end %>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-between text-center py-1">
              <div>
                <p class="mb-1 h5"><%= @comments_count %></p>
                <p class="small text-muted mb-0">Comentarios</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5">
                <%= @count_photo %>
                </p>
                <p class="small text-muted mb-0">Fotos</p>
              </div>
              <div>
                <a id="as" data-bs-toggle="modal" data-bs-target="#Modalhcc">
                <p class="mb-1 h5" for="as"><%= @hccs %></p>
                <p class="small text-muted mb-0">HCC</p>
                </a>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black ">
            <div class="mb-5 none">
              <p class="lead fw-normal mb-1">Detalles del diseño</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                <p class="font-italic mb-1"><strong>Responsable: </strong> <br> <%=  @design.responsible  %></p> <br>
                <p class="font-italic mb-1"><strong>Última revisión del plano: <br> </strong> <%=  @design.revision  %></p> <br>
                <p class="font-italic mb-1"><strong>Linea de producción: </strong> <br> <%=  @design.line  %></p> <br>
                <% if @user.role == "engineering_manager" || @user.role == "engineer" %>
                <p class="font-italic mb-1"><strong>Estatus: </strong> <br> <%=  @design.status  %></p> <br>
                <p class="font-italic mb-1"><strong>Link visor 3D: </strong> <br> <%=  @design.autodesk_link  %></p> <br>
                <p class="font-italic mb-1"><strong>Ruta del servidor: </strong> <br> <%=  @design.server_path  %></p> <br>
                <% end %>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0">Últimas fotos</p>
              <p class="mb-0"><a data-bs-toggle="modal" data-bs-target="#photoModal" class="text-muted">Ver todo</a></p>
            </div>
            <div class="row g-2">
            <% @lastphotos.each do |f| %>
              <div class="col-lg-6 col-md-12 mb-2 d-flex justify-content-center">
              <%= image_tag f , class: "w-lg-50 w-md-100  rounded-3 img-fluid", style: "height: 300px;" %>
              </div>
            <%end %>
            </div>
            <div class="">
              <div class="row d-flex justify-content-center">
                <div>
                  <div class="card">
                    <div class="card-body p-4">
                      <h4 class="text-left font-italic mb-4 pb-2">Comentarios del diseño</h4>
                      <%= render "comments/commets_form", comment: @comment, user: @user, design: @design %>
                      <%= render "comments/commets", comments: @comments, answer: @answer, user: @user, answers: @answers %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%# profile ends %>
<%# modal photos %>
<div class="modal fade " id="photoModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content bg-black">
      <div class="modal-body">
          <div id="carousel">
            <figure id="spinner">
              <% @allphotos.each do |item| %>
                <%= image_tag item , class: "w-lg-50 w-md-100  rounded-3 img-fluid", style: "height: 300px;" %>
              <% end %>
            </figure>
          </div>
          <span style="float:left" class="ss-icon" onclick="galleryspin('-')">&lt;</span>
          <span style="float:right" class="ss-icon" onclick="galleryspin('')">&gt;</span>
      </div>
    </div>
  </div>
</div>
<%# modal photos end %>
<%# modal hcc %>
<div class="modal fade" id="Modalhcc" tabindex="-1" aria-labelledby="ModalhccLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalhccLabel">HCCs</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">HCC</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% @hcc.each_with_index do |item, index| %>
            <tr>
              <th scope="row"><%= index %></th>
              <td><%= item.user %></td>
              <td><%= item.comment %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>
<%# modal hcc end %>
<div class="pop">
        <div class="pop-img">
            <img src="#" alt="" />
        </div>
    </div>
<script>
  var angle = 0;
  function galleryspin(sign) {
    spinner = document.querySelector("#spinner");
    if (!sign) { angle = angle + 45; } else { angle = angle - 45; }
    spinner.setAttribute("style","-webkit-transform: rotateY("+ angle +"deg); -moz-transform: rotateY("+ angle +"deg); transform: rotateY("+ angle +"deg);");
  }
</script>
<script>
 $(document).ready(function() {
  const previewImg = document.querySelectorAll('.img-wrapper img');
  const modalImg = document.querySelector('.pop-img img');
  const modal = document.querySelector('.pop');
  previewImg.forEach((images) => {
      images.addEventListener('click', () => {
          modal.classList.add('open');
          let imgSrc = images.src;
          modalImg.src = imgSrc;
          console.log(modalImg.src);
      });
  });

  modal.addEventListener('click', e => {
      if (e.target.classList.contains('pop')) {
          modal.classList.remove('open');
      }
  });

   });
</script>