config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :comments, only: %i[show create new edit update destroy]
  resources :answers

  get '/user', to: "designs#index", as: :user_root
  resources :designs
  get '/all_designs', to: 'designs#all_designs', as: :all_designs
  resources :requests, only: %i[new show edit update create destroy]
  get '/requests', to: 'requests#all_requests', as: :all_requests
  get '/new_project', to: 'requests#new_project', as: :new_project

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :annex
  has_many :answer, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show,:edit,:update,:destroy]
  def create
    @comment = Comment.new(comment_params)

    authorize @comment
    if @comment.save
      redirect_to design_path(@comment.design_id), notice: 'Comentario realizado con Exito'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @comment = Comment.new
  end

  def edit
    @user = current_user
  end

  def update

    @id = @comment.design_id
    if @comment.update(comment_params)
      redirect_to design_path(@id), notice: 'Comentario Actualizado'
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @id = @comment.design_id
    if @comment.destroy
      redirect_to design_path(@id), notice: 'Comentario Eliminado'
    else
      render :edit, status: unprocessable_entity
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:design_id, :user, :comment, :hcc, :annex)
  end
end

app/views/comments/_commets.html.erb
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <% @cont = 1 %>
            <% @comments.each do |f| %>
            <div class="d-flex flex-start mb-3">
                <b class="capital" ><%= f.user.split(" ")[0][0] + f.user.split(" ")[1][0] %></b>
                <div class="flex-grow-1 flex-shrink-1">
                    <div>
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="m-2">
                               <b><%=f.user %></b> <span class="small">
                               <% if f.hcc == "activo" %>
                                 - HCC
                               <% end %>
                               </span>
                            </p>
                            <div>
                            <% if f.user == @user.responsible %>
                              <a href=" <%= edit_comment_path(f.id) %>" class="m-2"><i class="fa-solid fa-pen-to-square link-dark"></i></a>
                              <%=link_to "" , comment_path(f.id), method: "delete" ,data:
                                {confirm: 'Desea eliminar este comentario?' },class: "fa-solid fa-trash-can m-2 link-dark" %>
                            <% end %>
                            </div>
                        </div>
                        <p class="small mb-0">
                            <%= f.comment%>
                        </p>
                        <p class="small mb-0 img-wrapper">
                        <% if f.annex.present? %>
                          <%= image_tag f.annex , class: "w-lg-50 w-md-100 rounded-3 img-fluid", style: "height: 300px;" %>
                        <% end %>
                        </p>
                        <a class="btn btn-outline-dark m-2 rounded-pill sizebtn" data-bs-toggle="modal" data-bs-target="#modal<%=@cont%>"><span class="small">Responder</span></a>
                    </div>
                </div>
            </div>
            <!--modal-->
            <div class="modal fade" id="modal<%=@cont%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Respuesta</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= render "answers/answer_form" , comment: f.id, answer: @answer, user: @user %>
                  </div>

                </div>
              </div>
            </div>
            <!--modal-->
            <% @cont = @cont + 1 %>
            <% @answers.each do |l| %>
            <% if f.id==l.comment_id %>
            <div class="d-flex flex-start mt-4 m-5">
                <b class="capital" ><%= l.user.split(" ")[0][0] + l.user.split(" ")[1][0] %></b>
                <div class="flex-grow-1 flex-shrink-1">
                    <div>
                        <div class="d-flex justify-content-between align-items-center">
                            <p class="m-2">
                            <b >
                                <%= l.user %>
                            </b>
                            </p>

                        </div>
                        <p class="small mb-0">
                            <%=l.answer %>
                        </p>
                        <p class="small mb-0 img-wrapper">
                            <% if l.answerimg.present? %>
                            <%= image_tag l.answerimg , class: "w-lg-50 w-md-100 rounded-3 img-fluid", style: "height: 300px;" %>
                            <% end %>
                        </p>
                        <% if l.user == @user.responsible %>
                          <a href=" <%= edit_answer_path(l.id) %>" class="m-1"><i class="fa-solid fa-pen-to-square link-dark"></i></a>
                        <%=link_to "" , answer_path(l.id), method: "delete" ,data:
                                            {confirm: 'Desea eliminar este comentario?' },class: "fa-solid fa-trash-can link-dark" %>
                        <% end %>

                    </div>
                </div>
            </div>
            <% end %>
            <% end %>
            <% end %>
        </div>
    </div>

app/views/comments/_commets_edit.html.erb
<section class="vh-100 back" >
  <div class="container py-5 h-100" style="overflow-y: hidden">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">

            <div class="col-md-10 col-lg-12 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">
                <%= simple_form_for(comment) do |f| %>
                  <div class="row">
                  <%= f.input :design_id,as: :hidden, input_html: { readonly: "readonly"} %>
                  <%= f.input :user,as: :hidden, input_html: { readonly: "readonly" }%>
                  <%= f.input :comment, as: :text, label: "Comentario" %>
                  <div class="col-md-2">
                  <label for="lol" >
                  <i class="fa-solid fa-camera"></i>
                  <%= f.input :annex,as: :file, input_html: {style: "display: none; width:10px; ", id:"lol"}, label: false %>
                  </label>
                  </div>
                  <div class="col-md-10 d-md-flex justify-content-md-end ">
                  <%= f.submit "Guardar", class: "btn btn-primary" %>
                  </div>
                    <%= f.input :hcc, as: :boolean, checked_value: "activo",unchecked_value: "inactivo",class: "btn btn-primary col-2" %>
                  </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/comments/_commets_form.html.erb
<div class="container">
  <%= simple_form_for(comment) do |f| %>
      <div class="row">
      <%= f.input :user,as: :hidden, input_html: {value: user.responsible, readonly: "readonly" }%>
      <%= f.input :design_id,as: :hidden, input_html: {value: design.id, readonly: "readonly"} %>
      <%= f.input :comment, as: :text, label: "Comentario" %>
      <div class="col-md-2">
      <label for="lol" >
      <i class="fa-solid fa-camera"></i>
      <%= f.input :annex,as: :file, input_html: {style: "display: none; width:10px; ", id:"lol"}, label: false %>
      </label>
      </div>
      <div class="col-md-10 d-md-flex justify-content-md-end ">
      <%= f.submit "Guardar", class: "btn btn-primary rounded-pill " %>
      </div>
        <%= f.input :hcc, as: :boolean, checked_value: "activo",unchecked_value: "inactivo",class: "btn btn-primary col-2" %>
      </div>
      </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= render "commets_edit", comment: @comment, user: @user, design: @design %>