config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :comments, only: %i[show create new edit update destroy]
  resources :answers

  get '/user', to: "designs#index", as: :user_root
  resources :designs
  get '/all_designs', to: 'designs#all_designs', as: :all_designs
  resources :requests, only: %i[new show edit update create destroy]
  get '/requests', to: 'requests#all_requests', as: :all_requests
  get '/new_project', to: 'requests#new_project', as: :new_project

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :design
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[show edit update destroy]
  def all_requests
    @requests = policy_scope(Request)
    @designs = Design.all
    authorize @requests
    @user = current_user
  end

  def new_project
    @request = Request.new
    @user = current_user
    authorize @request
  end

  def new
    @request = Request.new
    @user = current_user
    @designs = Design.all
    authorize @request
  end

  def create
    @request = Request.new(request_params)
    @designs = Design.all
    authorize @request
    if @request.save
      redirect_to all_requests_path
    else
      render "new"
    end
  end

  def update
    @request.update(request_params)
    redirect_to all_requests_path
  end

  def edit
    @designs = Design.all
  end

  def show
    @user = current_user
  end

  def destroy
    @request.destroy
    authorize @request
    redirect_to requests_path
  end

  private

  def set_request
    @request = Request.find(params[:id])
    authorize @request
  end

  def request_params
    params.require(:request).permit(
      :project_number_req, :project_name_req,
      :required_date, :status, :design_id
    )
  end
end

app/views/requests/all_requests.html.erb
<div class="header">

  <!--Content before waves-->
  <div class="inner-header flex">
    <h1>Solicitudes de diseño</h1>
  </div>

  <!--Waves Container-->
  <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7)" />
    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
    <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
    </svg>
  </div>
  <!--Waves end-->

</div>
<!--Header ends-->

<div class="d-flex flex-column" id="home-icon">
  <%= link_to image_tag("home"), designs_path%>
  <p>Regresar al inicio</p>
</div>

<div id="all-designs-table">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary rounded-pill position-absolute top-0 end-0 m-3 shadow-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Nueva solicitud
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Nueva solicitud de diseño</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body d-flex justify-content-between">
          <%= link_to "Proyecto Existente", new_request_path, class: "btn btn-outline-secondary rounded-pill" %>
          <%= link_to "Proyecto Nuevo", new_project_path, class: "btn btn-outline-success rounded-pill" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="container" class="m-5">
    <table class="table table-hover data-table">
      <thead>
        <tr>
          <th scope="col">Número de proyecto</th>
          <th scope="col">Nombre del proyecto</th>
          <th scope="col">Fecha requerida</th>
          <th scope="col">Estatus <br>🚩|✅</th>
          <th scope="col">Request</th>
          <th scope="col">Delete</th>
          <th scope="col">Creación</th>
        </tr>
      </thead>
      <tbody>
        <% @requests.each do |request| %>
        <tr>
          <th scope="row"><%= request.project_number_req %></th>
          <td><%= request.design.project_name %></td>
          <td><%= request.required_date %></td>
          <td><%= ((request.design.id == 1) || (request.status == "pending")) ? '🚩': '✅' %></td>
          <td><%= request.created_at.in_time_zone("Mexico City").strftime("%Y/%m/%d %H:%m") %></td>
          <td><%= link_to "Editar", edit_request_path(request), class: "btn btn-outline-dark rounded-pill" %></td>
          <td><%= link_to "Eliminar", request_path(request), method: "delete", class: "btn btn-outline-danger rounded-pill" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requests/edit.html.erb
<%= link_to "Todas las solicitudes de diseño", all_requests_path, class: "btn btn-secondary" %>
<br>
<div class="container">

  <%= simple_form_for(@request) do |f| %>

    <div class="form-group">
      <%= f.input :project_number_req, label: "Número de proyecto solicitado" %>
      <%= f.input :project_name_req, label: "Nombre del proyecto solicitado" %>
      <%= f.input :required_date, as: :date, html5: true, label: "Fecha requerida de entrega" %>
    </div>

    <div class="form-group">
      <%= f.select :design_id, @designs.map { |d| [d.project_number + " | " + d.project_name, d.id]}, {}, class: "form-control" %>
      <%= f.select :status, [['Atendido', 'done'], ['Pendiente','pending']] %>
    </div>

    <div class="form-group">
      <%= f.submit "Actualizar solicitud", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/requests/new.html.erb
<br><br><br>

<div class="container">
  <%= simple_form_for(@request) do |f| %>
    <%= f.select :project_number_req, @designs.map { |d| [d.project_number + " | " + d.project_name, d.project_number]}, {prompt: "Elige un proyecto existente..."}, class: "form-control" %>
    <%= f.input :required_date, as: :date, html5: true %>
    <%= f.select :status, [['Pendiente','pending'],['Atendido', 'done']] %>
    <%= f.input :design_id, input_html: { value: 1 }, as: "hidden" %>
    <%= f.submit "Guardar", class: "modal-button" %>
  <% end %>
</div>

app/views/requests/new_project.html.erb
<br><br><br>

<div class="container">
  <%= simple_form_for(@request) do |f| %>

<div class="container register" id="test-div-form">
        <div class="row">
            <div class="col-md-3 register-left">
                <%= image_tag "favicon.ico" %>
                <h3>Hola, <%= @user.responsible %></h3>
                <p class="text-light">...</p>
                <div class="d-flex justify-content-between">
                  <%= f.submit "Guardar", class: "modal-button" %>
                  <%= link_to "Cancelar", designs_path, class: "btn btn-outline-light rounded-pill" %>
                </div>
            </div>

            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Solicitud de nuevo diseño</h3>
                        <div class="row register-form ">
                            <div class="col-md-9 mx-auto">
                                <div class="form-group">
                                <%= f.input :project_number_req, label: "Número de proyecto" %>
                                </div>
                                <div class="form-group">
                                 <%= f.input :required_date, as: :date, html5: true %>
                                </div>
                                <div class="form-group">
                                  <%= f.select :status, [['Pendiente','pending'],['Atendido', 'done']] %>
                                </div>
                                <div class="form-group">

                                </div>
                                <div class="form-group">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>
 <% end %>

app/views/requests/show.html.erb
<%= @request.project_number_req %> <br>
<%= @request.project_name_req %>